/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.npsc.login;

import com.npsc.dao.FlatDAO;
import com.npsc.dao.HouseDAO;
import com.npsc.dao.impl.FlatDAOImpl;
import com.npsc.dao.impl.HouseDAOImpl;
import com.npsc.dao.impl.SecretaryDaoImpl;

import com.npsc.entity.FinalTableModel;
import com.npsc.entity.Flat;
import com.npsc.entity.FlatModel;
import com.npsc.entity.House;
import com.npsc.entity.HouseModel;
import com.npsc.file.WriteReadFile;
import com.npsc.file.WriteReadFileFlat;
import com.npsc.file.WriteReadFileHouse;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ashwin
 */
public class SecDashboard extends javax.swing.JFrame {
private List<House> houseList=null;
private List<Flat> flatList=null;
    public static House house=null;
     public static Flat flat=null;
    private HouseDAO houseDAO=new HouseDAOImpl();
    private FlatDAO flatDAO=new FlatDAOImpl();
    private List<House> filteredHouse=new ArrayList<>();
    
     private List<Flat> filteredFlat=new ArrayList<>();
    
    /**
     * Creates new form SecDashboard
     */
    public SecDashboard() {
        house=null;
      
        initComponents();
      //jTable1.repaint(); 
        jTable1.getTableHeader().setFont(new Font("Segeo UI",Font.BOLD,12));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(32,136,203));
          jTable1.getTableHeader().setForeground(new Color(255,255,255));
          jTable1.setRowHeight(25);
          
          
          String pattern = "MM/dd/yyyy HH:mm:ss";


        DateFormat df = new SimpleDateFormat(pattern);
Date today = Calendar.getInstance().getTime();        
String todayAsString = df.format(today);


  
        jLabel5.setText(todayAsString);
          
          flatTable.getTableHeader().setFont(new Font("Segeo UI",Font.BOLD,12));
        flatTable.getTableHeader().setOpaque(false);
        flatTable.getTableHeader().setBackground(new Color(32,136,203));
          flatTable.getTableHeader().setForeground(new Color(255,255,255));
          flatTable.setRowHeight(25);
           houseList=houseDAO.getAll();
           flatList=flatDAO.getAll();
           
         filteredHouse=houseDAO.getBySecretaryId();
         filteredFlat=flatDAO.getBySecretaryId();
          jLabel3.setText("Welcome"+" "+SecretaryDaoImpl.sec.getUserName());
        if (filteredHouse !=null){
                  fetch();
        }
        
        if(filteredFlat!=null){
          fetchFlat();   
           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        houseSaleHistory = new javax.swing.JButton();
        deleteHouse = new javax.swing.JButton();
        deleteHouse1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        exit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        updateHouse = new javax.swing.JButton();
        addFlat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        flatSaleHistory = new javax.swing.JButton();
        addHouse = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        flatTable = new javax.swing.JTable();
        updateHouse1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(100, 160, 220));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Secretary DashBoard");

        houseSaleHistory.setIcon(new javax.swing.ImageIcon("F:\\NationalPropertySalesCompany\\icons8-activity-history-50.png")); // NOI18N
        houseSaleHistory.setText("View House Sale History");
        houseSaleHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseSaleHistoryActionPerformed(evt);
            }
        });

        deleteHouse.setIcon(new javax.swing.ImageIcon("F:\\NationalPropertySalesCompany\\icons8-delete-48.png")); // NOI18N
        deleteHouse.setText("Delete House");
        deleteHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteHouseActionPerformed(evt);
            }
        });

        deleteHouse1.setIcon(new javax.swing.ImageIcon("F:\\NationalPropertySalesCompany\\icons8-delete-48.png")); // NOI18N
        deleteHouse1.setText("Delete Flat");
        deleteHouse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteHouse1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("F:\\NationalPropertySalesCompany\\icons8-sale-100.png")); // NOI18N
        jButton1.setText("Sale House");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "address", "rooms", "sellingPrice"
            }
        ));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(18);
        jTable1.setSelectionBackground(new java.awt.Color(255, 102, 102));
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });

        exit.setIcon(new javax.swing.ImageIcon("F:\\NationalPropertySalesCompany\\icons8-exit-sign-64.png")); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("F:\\NationalPropertySalesCompany\\icons8-sale-100.png")); // NOI18N
        jButton2.setText("Sale Flat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        updateHouse.setIcon(new javax.swing.ImageIcon("F:\\NationalPropertySalesCompany\\icons8-update-tag-32.png")); // NOI18N
        updateHouse.setText("Update House");
        updateHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateHouseActionPerformed(evt);
            }
        });

        addFlat.setIcon(new javax.swing.ImageIcon("F:\\NationalPropertySalesCompany\\icons8-add-column-48.png")); // NOI18N
        addFlat.setText("Add Flat");
        addFlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlatActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\NationalPropertySalesCompany\\icons8-home-64.png")); // NOI18N
        jLabel2.setText("Manage House ");

        flatSaleHistory.setIcon(new javax.swing.ImageIcon("F:\\NationalPropertySalesCompany\\icons8-activity-history-50.png")); // NOI18N
        flatSaleHistory.setText("View Flat Sale History");
        flatSaleHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flatSaleHistoryActionPerformed(evt);
            }
        });

        addHouse.setBackground(new java.awt.Color(0, 153, 0));
        addHouse.setIcon(new javax.swing.ImageIcon("F:\\NationalPropertySalesCompany\\icons8-add-column-48.png")); // NOI18N
        addHouse.setText("Add House");
        addHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHouseActionPerformed(evt);
            }
        });

        flatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "address", "noOfRooms", "sellingPrice"
            }
        ));
        flatTable.setFocusable(false);
        flatTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        flatTable.setRowHeight(25);
        flatTable.setSelectionBackground(new java.awt.Color(232, 57, 95));
        flatTable.setShowVerticalLines(false);
        flatTable.getTableHeader().setReorderingAllowed(false);
        flatTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flatTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(flatTable);

        updateHouse1.setIcon(new javax.swing.ImageIcon("F:\\NationalPropertySalesCompany\\icons8-update-tag-32.png")); // NOI18N
        updateHouse1.setText("Update Flat");
        updateHouse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateHouse1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Raavi", 0, 18)); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("F:\\NationalPropertySalesCompany\\icons8-condo-30.png")); // NOI18N
        jLabel4.setText("Manage Flats");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton1)
                        .addGap(36, 36, 36)
                        .addComponent(houseSaleHistory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(63, 63, 63)
                        .addComponent(flatSaleHistory)
                        .addGap(81, 81, 81))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addHouse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateHouse)
                                .addGap(18, 18, 18)
                                .addComponent(deleteHouse))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(addFlat)
                                .addGap(26, 26, 26)
                                .addComponent(updateHouse1)
                                .addGap(27, 27, 27)
                                .addComponent(deleteHouse1)))
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(68, 68, 68)))
                        .addComponent(exit)
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateHouse1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addHouse)
                                .addComponent(updateHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deleteHouse)
                                .addComponent(addFlat)
                                .addComponent(deleteHouse1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(houseSaleHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(flatSaleHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1245, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        houseList=HouseDAOImpl.houseList;
                
        WriteReadFileHouse.writeFile(houseList);
        
        flatList=FlatDAOImpl.flatList;
        
        WriteReadFileFlat.writeFile(flatList);
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void addHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHouseActionPerformed
        setVisible(false);
        AddHouse adHouse=new AddHouse();
        adHouse.setVisible(true);
    }//GEN-LAST:event_addHouseActionPerformed

    private void addFlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlatActionPerformed
        
              setVisible(false);
        AddFlat ad=new AddFlat();
        ad.setVisible(true);
      //  ad.passHouse(house);
       
    }//GEN-LAST:event_addFlatActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        initDetail(jTable1.getSelectedRow());
    }//GEN-LAST:event_jTable1MouseClicked

    private void updateHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateHouseActionPerformed
        setVisible(false);
        UpdateHouse u=new UpdateHouse();
        u.setVisible(true);
    }//GEN-LAST:event_updateHouseActionPerformed

    private void deleteHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteHouseActionPerformed
       //house.setSecretary(SecretaryDaoImpl.sec);
        boolean x= houseDAO.delete(house);
       if(x){
              JOptionPane.showMessageDialog(null,"House is deleted");
              //jTable1.repaint();
              filteredHouse=houseDAO.getBySecretaryId();
             jTable1.setModel(new HouseModel(filteredHouse));
             jTable1.setPreferredScrollableViewportSize(new Dimension(450,63));
        jTable1.setFillsViewportHeight(true);

        JScrollPane js=new JScrollPane(jTable1);
        js.setVisible(true);
        add(js);
             // WriteReadFileHouse.writeFile(HouseDAOImpl.houseList);
            // new SecDashboard();
             house=null;
       }
    }//GEN-LAST:event_deleteHouseActionPerformed

    private void updateHouse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateHouse1ActionPerformed
        setVisible(false);
        UpdateFlat u=new UpdateFlat();
        u.setVisible(true);
    }//GEN-LAST:event_updateHouse1ActionPerformed

    private void deleteHouse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteHouse1ActionPerformed
       flat.setSec(SecretaryDaoImpl.sec);
        boolean x= flatDAO.delete(flat);
       if(x){
              JOptionPane.showMessageDialog(null,"Flat is deleted");
            // tableModel.fireTableDataChanged();
               filteredFlat=flatDAO.getBySecretaryId();
             flatTable.setModel(new FlatModel(filteredFlat));
       }
              
    }//GEN-LAST:event_deleteHouse1ActionPerformed

    private void flatTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flatTableMouseClicked
        initDetailFlat(flatTable.getSelectedRow());
    }//GEN-LAST:event_flatTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(house==null){
            JOptionPane.showMessageDialog(null,"Please select House");
        }
        else{
            setVisible(false);
            SaleHouse sale=new SaleHouse();
            sale.setVisible(true);
            sale.setSaleType("house");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void houseSaleHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseSaleHistoryActionPerformed
            setVisible(false);
            SaleHistory sh=new SaleHistory();
            sh.setVisible(true);
    }//GEN-LAST:event_houseSaleHistoryActionPerformed

    private void flatSaleHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flatSaleHistoryActionPerformed
        setVisible(false);
            SaleHistoryFlat sh=new SaleHistoryFlat();
            sh.setVisible(true);
    }//GEN-LAST:event_flatSaleHistoryActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
            SaleFlat sh=new SaleFlat();
            sh.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecDashboard().setVisible(true);
            }
        });
    }
    
    public void fetch(){
        houseDAO=new  HouseDAOImpl();
//        houseList=new ArrayList<>();
//           houseList=houseDAO.getAll();
      
         if (filteredHouse !=null){
             
              jTable1.setVisible(true);
    jTable1.setModel(new HouseModel(filteredHouse));
    jScrollPane1.setViewportView(jTable1);
         }
        
  
    }
    
    protected void initDetail(int selectedRow) {
        house = filteredHouse.get(jTable1.convertRowIndexToModel(selectedRow));
    
      
    }
    
       protected void initDetailFlat(int selectedRow) {
        flat = filteredFlat.get(jTable1.convertRowIndexToModel(selectedRow));
      
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFlat;
    private javax.swing.JButton addHouse;
    private javax.swing.JButton deleteHouse;
    private javax.swing.JButton deleteHouse1;
    private javax.swing.JButton exit;
    private javax.swing.JButton flatSaleHistory;
    private javax.swing.JTable flatTable;
    private javax.swing.JButton houseSaleHistory;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton updateHouse;
    private javax.swing.JButton updateHouse1;
    // End of variables declaration//GEN-END:variables

    private void fetchFlat() {
        flatTable.setVisible(true);
       // flatList=new ArrayList<>();
        flatTable.setModel(new FlatModel(filteredFlat));
        jScrollPane2.setViewportView(flatTable);
    }

    void setTable() {
    jTable1.repaint();
    }
}
